### ISSUE TITLE
import qe_minesweeper not reading list/array

### ISSUE THREAD

**Issue by TAYLANAKAY** [RICOHub01/QNG23-Challenge#1]
QuantumGuard attempted to submit the answers for Stage0 via import qe_minesweeper however, the function does not accept list/array. That is quite weird because the input data is all in arrays. When we attempted to submit our answers in json_serializable format, it turned out obvious that the system does not expect data to be submitted in that format either.

This hurdle is just another one on top of many other data engineering related ones such as the absence of metadata.

We are happy to provide our answers for Stage0 either by sharing our python code or providing a csv file with the Challenge team.

**Comment by RDC-Mitchell** [comment]
Hi Taylan,

Before you input the list/array into the submit_answers() function, can you try adding the `.tolist()` function at the end of the array.

It can look like either:
```python
team_estimates = [...]
team_estimates_changed = team_estimates.tolist()
submit_answers(team_estimates_changed, 0, token)
```
or
```python
team_estimates = [...]
submit_answers(team_estimates.tolist(), 0, token)
```

This fix changes the list from a numpy array to regular python list- let me know if it works.

**Comment by TAYLANAKAY** [comment]
thanks Mitchell

`Created on Tue Oct 24 17:23:45 2023
```python
@author: Team QuantumGuard
### STAGE_0 Submission
import h5py  # heavy lifting hdf5 reading
import numpy as np
import pandas as pd
import requests
import os
import qe_minesweeper
#
all_mine_positions = []
#
#
file_path = 'C:/Users/61414/stage1_training_data.h5'
with h5py.File(file_path, 'r') as hf:
    # 
    for dataset_name in hf.keys():
        dataset = hf[dataset_name]
        # 
        if "mine_position" in dataset.attrs:
            mine_positions = dataset.attrs["mine_position"]
            all_mine_positions.append(mine_positions)

for i, mine_positions in enumerate(all_mine_positions):
    print(f"Mine positions for dataset {i + 1}:\n{mine_positions}")


our_answers = all_mine_positions

#investigate the number of mine positions across 1000 datasets 
#
file_path = 'C:/Users/61414/stage1_training_data.h5'
with h5py.File(file_path, 'r') as hf:
    # 
    dataset_keys = list(hf.keys())
    # 
    number_of_datasets = len(dataset_keys)
    print("Number of datasets in the file:", number_of_datasets)`
```
