### ISSUE TITLE
Stage1 submission this morning

### ISSUE THREAD

**Issue by TAYLANAKAY** [RICOHub01/QNG23-Challenge#3]
Hi QNG23 Challenge Admin Team,

Team QuantumGuard made a minor mistake in naming its submission for Stage1 this morning. We fed our model results via response = qe_minesweeper.submit_answers(our_answers, 0, "our authentication code") , instead of response = qe_minesweeper.submit_answers(our_answers, 1, "our authentication code"). Stage parameter was entered incorrectly by mistake.

We are happy to provide our code that generates answers if you did not get our results.

regards
QuantumGuard

**Comment by TAYLANAKAY** [comment]
Team QuantumGuard just made the correction with the right parameter and resubmitted to the server.

**Comment by RDC-Mitchell** [comment]
Hi @TAYLANAKAY, your corrected response has been received and we are happy to treat your misconfigured attempt as the submission time. Have a good weekend!
