### ISSUE TITLE
estimate_check: ValueError

### ISSUE THREAD

**Issue by MrAdamStewart** [RICOHub01/QNG23-Challenge#4]
Hi, we get a ValueError when using the estimate_check function in qe_minesweeper. 

After looking at the documentation for the distance calculator it looks like it will return ValueError when the two vectors passed are not the same shape.
[https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.directed_hausdorff.html]

So if we have guessed too many mines in a scenario within the 10% false positive limit, then 'mine_positions' and 'mine_estimates' are not the same length and the distance calculation in estimate_check will return ValueError. 

Cheers,
Adam

**Comment by RDC-Mitchell** [comment]
Hi @MrAdamStewart,

I noted this error and pushed a fix recently (80f639c), you can download the qe_minesweeper.py module from the repo (or just directly copy the code section for estimate_check) and the estimate_check function will now transpose the arrays from 2xN to be Nx2 before attempting a directed hausdorff function.

**Comment by MrAdamStewart** [comment]
@RDC-Mitchell  
Thanks for your response. You are correct, this is my mistake for not running the latest version. I've copied across the updated function and everything is working fine. 

Cheers

**Comment by RDC-Mitchell** [comment]
No significant mistake @MrAdamStewart, I'm here to help, and sometimes that involves elevating silent fixes. 

Excited to see your progress.
