### ISSUE TITLE
TypeError: Object of type int64 is not JSON serializable

### ISSUE THREAD

**Issue by MrAdamStewart** [RICOHub01/QNG23-Challenge#7]
Hi, I'm getting a long error when using the move function for the online drone sim class. 

The code which I'm trying to run  feeds the position to move into the ds.move function. Which was working fine for the offline dataset. our drone looks like it has actually moved one step already. 

for i,j in survey_matrix:
    ds.move(pos_east=i,pos_north=j)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_1420724/3540143483.py in <module>
      4 ds_dataU = np.zeros((101, 101))
      5 for i,j in survey_matrix:
----> 6     ds.move(pos_east=i,pos_north=j)
      7     ds_dataE[i,j] = ds.b_east_drone[-1]
      8     ds_dataN[i,j] = ds.b_north_drone[-1]

~/Dropbox/QNG/QNG23-Challenge-3.0.0/qe_minesweeper.py in move(self, pos_east, pos_north)
    289 
    290         # ONLINE ACTIONS OCCUR HERE
--> 291         self.perform_read()
    292 
    293         self.time_step += 1

~/Dropbox/QNG/QNG23-Challenge-3.0.0/qe_minesweeper.py in perform_read(self)
    267     def perform_read(self):
    268         payload = {"move":[self.position_East[-1],self.position_North[-1]]}
--> 269         response = post_to_server(payload, self.ref)
    270         data = response.json()
    271         b_noise = data['b_noise']

~/Dropbox/QNG/QNG23-Challenge-3.0.0/qe_minesweeper.py in post_to_server(payload, ref)
    109 
    110 def post_to_server(payload, ref=""):
--> 111     return requests.post(URL+ref, json=payload, headers={'QeC':QEC})
    112 
    113 def get_from_server(payload, ref=""):

TypeError: Object of type int64 is not JSON serializable

**Comment by MrAdamStewart** [comment]
I'm thinking that maybe we can converting from numpy int to python int before calling the move function? i.e ds.move(pos_east=int(i),pos_north=int(j))

If you can reset this scenario for us then I can try again.

**Comment by RDC-Mitchell** [comment]
Hi Adam,
That's my immediate recommendation- seems like the matrix_survey is making itself with int64's instead of ints. Let me if that doesn't work.

**Comment by MrAdamStewart** [comment]
@RDC-Mitchell , thank you, yes that seems to have fixed the problem. I tried it on the next scenario, the drone is moving and our data is populating. I'm guessing when I try the one that gave us the error again the local 'move' might disappear. If it doesn't work I will let you know

**Comment by RDC-Mitchell** [comment]
@MrAdamStewart We are getting your activity here so that's good signs on both ends.

So, for the scenario 0 drone, we received the creation request and then had the issue with the move. 
If the code functions correctly, when you recreate the scenario 0 drone instance on your side, it should recognise the existence of the drone online and carry on from the beginning, since we never received and acted on the movement.

Let me know if there are any issues, if we wind up with a stray time increment I can fix that for you.
